### ISSUE TITLE
dependabot:  Move to Zig package-ecosystem when supported by dependabot.

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/cairo-zig#48]
# Move to Zig package-ecosystem when it's ready for Dependabot Workflow

## Summary

We currently use GitHub Actions and Git Submodules for dependency management as listed in our Dependabot configuration. Once the Zig package-ecosystem is fully supported by Dependabot, we should transition to using it for a more native and efficient workflow. This issue aims to track the progress and plan the migration.

### Current Dependabot Configuration

Here is our current Dependabot configuration:

```yaml
# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
```

### Tracking Issue

We are currently keeping an eye on this Dependabot core issue for Zig package-ecosystem support:

- [Dependabot Core Tracking Issue](https://github.com/dependabot/dependabot-core/issues/8166)

### Action Items

1. **Monitor the Tracking Issue**: Regularly check the status of the [Dependabot Core Tracking Issue](https://github.com/dependabot/dependabot-core/issues/8166) for updates on Zig package-ecosystem support.

2. **Update Documentation**: Once Zig is supported, update all relevant documentation to include the new ecosystem.

3. **Modify Dependabot Configuration**: Replace the GitHub Actions and Git Submodules ecosystems in `.github/dependabot.yml` with the Zig package-ecosystem.

4. **Testing**: Perform rigorous testing to ensure that the new Dependabot configuration works as expected.

5. **Communication**: Inform team members and contributors about the change.

## Additional Information

- Zig package manager documentation: [temporary doc](https://ziglang.org/download/0.11.0/release-notes.html#Package-Management))
- [Dependabot Documentation](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically)

## Timeline

TBD, dependent on the availability of Zig package-ecosystem support.

## Contacts

- For any security concerns, please contact [security@starkware.co](mailto:security@starkware.co).

Please feel free to add any other relevant information or action items to make this transition as smooth as possible.
